"""Create user and schedule tables

Revision ID: 54435a1083c9
Revises: 
Create Date: 2025-10-15 20:18:58.225509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54435a1083c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='사용자 고유 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 주소 (로그인 ID)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False, comment='일정 고유 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='일정 제목'),
    sa.Column('content', sa.Text(), nullable=True, comment='일정 상세 내용'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='일정 시작 시간'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='일정 종료 시간'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='삭제 여부'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='일정 소유자 ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_is_deleted'), 'schedules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_schedules_start_time'), 'schedules', ['start_time'], unique=False)
    op.create_index(op.f('ix_schedules_title'), 'schedules', ['title'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_title'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_start_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_is_deleted'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
