"""Add date column and modify time columns in schedules table

Revision ID: 95d25bf30d62
Revises: ad5a9d560c3a
Create Date: 2025-10-30 16:42:31.457816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95d25bf30d62'
down_revision: Union[str, None] = 'ad5a9d560c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('date', sa.Date(), nullable=False, comment='일정 날짜'))
    op.alter_column('schedules', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_comment='일정 시작 시간',
               existing_nullable=False)
    op.alter_column('schedules', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_comment='일정 종료 시간',
               existing_nullable=True)
    op.create_index(op.f('ix_schedules_date'), 'schedules', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_date'), table_name='schedules')
    op.alter_column('schedules', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='일정 종료 시간',
               existing_nullable=True)
    op.alter_column('schedules', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='일정 시작 시간',
               existing_nullable=False)
    op.drop_column('schedules', 'date')
    # ### end Alembic commands ###
