"""Change to start_time and end_time nullable option false in schedules table

Revision ID: cf120059b194
Revises: 5f57de99d9c7
Create Date: 2025-11-18 02:12:02.989896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf120059b194'
down_revision: Union[str, None] = '5f57de99d9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_comment='일정 종료 시간')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_comment='일정 종료 시간')
    # ### end Alembic commands ###
