"""create_job_histories_table

Revision ID: fe8bce9ff145
Revises: 665613919481
Create Date: 2025-12-16 08:41:52.133883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8bce9ff145'
down_revision: Union[str, None] = '665613919481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False, comment='작업명 (예: morning_briefing)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (SUCCESS, FAILED)'),
    sa.Column('details', sa.Text(), nullable=True, comment='상세 결과 또는 에러 메세지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_histories_id'), 'job_histories', ['id'], unique=False)
    op.create_index(op.f('ix_job_histories_job_name'), 'job_histories', ['job_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_histories_job_name'), table_name='job_histories')
    op.drop_index(op.f('ix_job_histories_id'), table_name='job_histories')
    op.drop_table('job_histories')
    # ### end Alembic commands ###
